### ISSUE TITLE
ActionController::InvalidAuthenticityToken  Error

### ISSUE THREAD

**Issue by rbazinet** [hopsoft/chatter#2]
I pulled down the code to play around with how reactive a Rails app can be and when trying to post a message I get the ActionController::InvalidAuthenticityToken error. 

I didn't see you have the problem in the video but I have it. If I skip :verify_authenticity_token in the posts controller, it works fine. Obviously not the solution. Is this something to do with StimulusReflex? Any thoughts would be appreciated.

**Comment by asadakbar** [comment]
I hit the issue as well, but while following along with youtube tutorial that goes with this. I replaced my ruby posts_controller with the one from this repo and restarted the server and then it worked. But then I put my controller code back and it still worked. So 🤷‍♂️.

**Comment by asadakbar** [comment]
Spoke too soon, hitting that same error again.

Adding a note as I looked up the issue on the sr repo and saw that devise hit the same type of error. I installed sr according to the youtube video and my session_store is set to `:cache_store` in the development.rb env file.

**Comment by leastbad** [comment]
Please run the following:
```
git clone git@github.com:hopsoft/chatter.git
cd chatter
bundle install && yarn install && rake db:setup && rake db:migrate && rails dev:cache
rails s
```
Now, open two windows and go to `localhost:3000` with each one. Finally, make a post.
This should *absolutely* just work. 100%

**Comment by rbazinet** [comment]
@leastbad I can confirm when I use these steps, the code runs as it should with no errors. When I go back to the original code I pulled down and try, I still get the same error. 

The code is exactly the same and when I setup the project I did as above, with the exception of rails dev:cache. I tried this on the code I had and still get the error.

I'd really like to know why the error is happening because everything seems identical.

**Comment by leastbad** [comment]
If you don't run `rails dev:cache` you will 100% see the problem that you're experiencing.

Perhaps I'm misunderstanding what you're saying?

**Comment by rbazinet** [comment]
@leastbad I tried caching in the version of the app and you are correct. Once I turned on the dev:cache it worked. You are not misunderstanding me, you have solved this problem.

What I don't understand is why running `rails dev:cache` needs to be run at all? Can you explain?

**Comment by leastbad** [comment]
It's been speculated upon, heavily, but as of the time of this writing, I haven't seen anyone suggest a conclusive explanation.

That said, we do mention the necessity to enable caching in development several times in the documentation - including the case where you clone into an existing project.

It would be amazing if you or anyone reading this had any theories.

Would you mind closing this issue?

**Comment by rbazinet** [comment]
I am going to investigate this and see why it's needed. I didn't run the command mainly because I didn't want caching turned on in dev.

Closing...

**Comment by leastbad** [comment]
Reasonable enough on its own, for sure. That said... is there a specific reason you don't want it on? I have yet to notice any undesirable behaviour in my projects with it on, but I've always felt like I'm probably missing something.

**Comment by rbazinet** [comment]
Honestly, I don't have a very good reason. As I work on Rails apps in dev I try to avoid caching just so some subtle issues aren't introduced. I haven't had issues per se, just trying not to run things automatically when not needed and have undesired behavior. I will keep an open mind about it going forward and use it.

This issue was interesting as it gave me undesired behavior *because* I didn't use it. Live and learn.

**Comment by leastbad** [comment]
Sounds like we're all in the same boat! 😀 

Our discussion on Discord has been pretty circular:

"StimulusReflex is broken. You broke my app!"
"Turn on caching"
"I did"
"Turn on caching"
"Oh, now I did. It shouldn't matter, but now it works"
"But why does it work?"
"Forcing people to cache *just because* isn't acceptable"
"We're not forcing them to use StimulusReflex, which seems to want to be cached"
"Why is turning caching on more of a problem than depending on a gem?"
"Because turning on caching changes how your app works in subtle ways (I clearly can't enumerate)"
"Requiring 3rd-party gems changes how your app works in subtle ways (you clearly can't enumerate)"
"Hitler."

**Comment by rbazinet** [comment]
I've been looking around a bit and there a bunch of talk out there. This article is kinda interesting and makes me think they are on to something, it's how I got around the problem before your message - https://appsignal.com/for/invalid_authenticity_token

**Comment by leastbad** [comment]
The official documentation on caching in development basically doesn't exist. All of the blog posts I can find on the subject address the complex issue of turning caching on and off. The GH PR threads I've found extensively debate the nuances of how best to support adding the caching flag. But so far as I can tell, there is no obvious, extant information as to the pros and cons of running caching in development, period. I strongly suspect that since page caching is no longer even part of Rails, that there might be a more benign explanation: nobody noticed that there's no longer a reason to have it turned off.

What I'm going to do, when I'm able, is go through ActionPack and figure out exactly what `perform_caching` actually does, starting with `caching.rb`. I'll write up anything I find.

https://github.com/rails/rails/search?q=perform_caching&unscoped_q=perform_caching

**Comment by leastbad** [comment]
Okay! I think that I finally have a handle on this.

As of SR v2.2.2 we dropped support for cookie-based session storage. In the [documentation](https://docs.stimulusreflex.com/deployment#session-storage) we recommend using `:cache_store` as the session storage, but give suggestions on how to use [ActiveRecord](https://github.com/rails/activerecord-session_store) as well.

The Rails default is :memory_store for the cache storage, although we recommend :redis_store (and require it for Expo).

However, if caching is turned off, then that means your session storage is being handled by :null_store, which suggests that whatever values you see returned are actual memory pointers to something we shouldn't be seeing. I suspect that this is *not good* but it's also out of the scope of this scenario.

Anyhow, the short answer is that unless you want to install the AR session store, you are likely going to **need** to enable caching and **want** to use Redis for caching.

Sigh. This seems obvious in hindsite.
